config/routes.rb
Kyotikaland::Application.routes.draw do
  resources :tags

  resources :landmarks do
    resources :keywords
  end
  root to: 'landmarks#index'

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :landmark
  attr_accessible :body
end

app/models/landmark.rb
class Landmark < ActiveRecord::Base
  attr_accessible :question, :answer1, :answer2, :answer3, :correct,
    :name, :latitude, :longitude, :url, :tag_tokens, :author, :hiragana
  attr_reader :tag_tokens

  validates :name, :hiragana, presence: true, uniqueness: true
  validates :correct, numericality: { greater_than_or_equal_to: 1,
                                      less_than_or_equal_to: 3 }

  has_many :keywords
  has_many :taggings
  has_many :tags, through: :taggings

  paginates_per 100

  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

  def self.available_locations
    self.where("latitude IS NOT NULL AND longitude IS NOT NULL")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :landmarks, through: :taggings

  def self.tokens(query)
    tags = where("name like ?", "%#{query}")
    if tags.empty?
      [{id: "<<<#{query}>>>", name: "New \"#{query}\""}]
    else
      tags
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :landmark
  belongs_to :tag
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  REALM = "a12CV4jsf2sArJs6Y"
  before_filter :authenticate

  private

  def authenticate
    name, pw = ENV["BASIC_AUTH_NAME"], ENV["BASIC_AUTH_PW"]
    return if name.nil? || pw.nil?
    users = { name => pw }
    authenticate_or_request_with_http_digest(REALM) do |username|
      users[username]
    end
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def create
    @landmark = Landmark.find(params[:landmark_id])
    @keyword = @landmark.keywords.create(params[:keyword])
    redirect_to landmark_path(@landmark)
  end

  def destroy
    @landmark = Landmark.find(params[:landmark_id])
    @keyword = @landmark.keywords.find(params[:id])
    @keyword.destroy
    redirect_to landmark_path(@landmark)
  end
end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  # GET /landmarks
  # GET /landmarks.json
  def index
    @search = Landmark.search(params[:q])
    @landmarks = @search.result.page params[:page]
    @locations = Landmark.available_locations

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @landmarks }
    end
  end

  # GET /landmarks/1
  # GET /landmarks/1.json
  def show
    @landmark = Landmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @landmark }
    end
  end

  # GET /landmarks/new
  # GET /landmarks/new.json
  def new
    @landmark = Landmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @landmark }
    end
  end

  # GET /landmarks/1/edit
  def edit
    @landmark = Landmark.find(params[:id])
  end

  # POST /landmarks
  # POST /landmarks.json
  def create
    @landmark = Landmark.new(params[:landmark])

    respond_to do |format|
      if @landmark.save
        format.html { redirect_to @landmark, notice: 'Landmark was successfully created.' }
        format.json { render json: @landmark, status: :created, location: @landmark }
      else
        format.html { render action: "new" }
        format.json { render json: @landmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /landmarks/1
  # PUT /landmarks/1.json
  def update
    @landmark = Landmark.find(params[:id])

    respond_to do |format|
      if @landmark.update_attributes(params[:landmark])
        format.html { redirect_to @landmark, notice: 'Landmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @landmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landmarks/1
  # DELETE /landmarks/1.json
  def destroy
    @landmark = Landmark.find(params[:id])
    @landmark.destroy

    respond_to do |format|
      format.html { redirect_to landmarks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags.tokens(params[:q]) }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/landmarks_helper.rb
module LandmarksHelper
  def name(landmark)
    if landmark.url.blank?
      landmark.name
    else
      link_to landmark.name, landmark.url, target: "_blank"
    end
  end

  def join_keywords(landmark)
    landmark.keywords.map { |k| k.body }.join(", ")
  end

  def join_tags(landmark)
    landmark.tags.map { |k| k.name }.join(", ")
  end

  def map_link(landmark)
    return "" unless key = ENV["GOOGLE_KEY"]
    if landmark.url.blank?
      ""
    else
      link_to "*", map_url(landmark, key, "", 17), target: "_blank"
    end
  end

  def map_link_all(locations)
    return "" if locations.count == 0
    return "" unless key = ENV["GOOGLE_KEY"]
    map_url(locations.first, key)
    locations.inject(map_url(locations.first, key)) do |query, l|
      point = point(l)
      query + "%7C#{point}"
    end
  end

  private

  def point(landmark)
    "#{landmark.latitude},#{landmark.longitude}"
  end

  def map_url(landmark, google_key, center="Kyoto", zoom=12)
    base = "http://maps.googleapis.com/maps/api/staticmap"
    attr = "?center=#{center}&zoom=#{zoom}&size=700x700&sensor=false"
    key = "&key=#{google_key}"
    point = point(landmark)
    marker = "&markers=%7C#{point}"
    base + attr + key + marker
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/landmarks/_form.html.erb
<%= form_for(@landmark) do |f| %>
  <% if @landmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landmark.errors.count, "error") %> prohibited this landmark from being saved:</h2>

      <ul>
      <% @landmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    名前<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    よみ（ひらがな）<br />
    <%= f.text_field :hiragana %>
  </div>
  <div class="field">
    緯度<br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    経度<br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    URL<br />
    <%= f.text_field :url, size: 60 %>
  </div>
  <div class="field">
    クイズ<br />
    <%= f.text_field :question, size: 70 %>
  </div>
  <div class="field">
    答1<br />
    <%= f.text_field :answer1 %>
  </div>
  <div class="field">
    答2<br />
    <%= f.text_field :answer2 %>
  </div>
  <div class="field">
    答3<br />
    <%= f.text_field :answer3 %>
  </div>
  <div class="field">
    正解番号<br />
    <%= f.number_field :correct %>
  </div>
  <div class="field">
    作成者<br />
    <%= f.text_field :author %>
  </div>
  <h2>タグ</h2>
  <div class="field">
    <%= f.text_field :tag_tokens, data: {load: @landmark.tags} %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/landmarks/edit.html.erb
<h1>ランドマーク編集</h1>

<%= render 'form' %>

<%= link_to '詳細表示', @landmark %> |
<%= link_to '戻る', landmarks_path %>

app/views/landmarks/index.html.erb
<h1>ランドマーク一覧</h1>

<%= link_to '新規作成', new_landmark_path %>
<%= link_to '地図で確認', map_link_all(@locations), target: "_blank" %>

<%= search_form_for @search do |f| %>
  <p>
    名前
    <%= f.text_field :name_cont %>
    作成者
    <%= f.text_field :author_cont, size: 10 %>
    <%= f.submit "検索" %>
  </p>
<% end %>

<%= paginate @landmarks %>
<%= @landmarks.total_count %>件中<%= @landmarks.offset_value %>
〜<%= @landmarks.offset_value + @landmarks.length %>件を表示しています。

<table>
  <tr>
    <th></th>
    <th><%= sort_link(@search, :name, "名前") %></th>
    <th><%= sort_link(@search, :hiragana, "よみ") %></th>
    <th>地図</th>
    <th>タグ</th>
    <th><%= sort_link(@search, :question, "クイズ") %></th>
    <th>答1</th>
    <th>答2</th>
    <th>答3</th>
    <th>正解番号</th>
    <th><%= sort_link(@search, :author, "作成者") %></th>
  </tr>

<% @landmarks.each do |landmark| %>
  <tr>
    <td><%= link_to '編集', edit_landmark_path(landmark) %></td>
    <td><%= name(landmark) %></td>
    <td><%= landmark.hiragana %></td>
    <td><%= map_link(landmark) %></td>
    <td><%= join_tags(landmark) %></td>
    <td><%= landmark.question %></td>
    <td><%= landmark.answer1 %></td>
    <td><%= landmark.answer2 %></td>
    <td><%= landmark.answer3 %></td>
    <td><%= landmark.correct %></td>
    <td><%= landmark.author %></td>
  </tr>
<% end %>
</table>

<br />

<%= paginate @landmarks %>

app/views/landmarks/new.html.erb
<h1>新規ランドマーク</h1>

<%= render 'form' %>

<%= link_to '戻る', landmarks_path %>

app/views/landmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>名前:</b>
  <%= @landmark.name %>
</p>

<p>
  <b>よみ:</b>
  <%= @landmark.hiragana %>
</p>

<p>
  <b>緯度:</b>
  <%= @landmark.latitude %>
</p>

<p>
  <b>経度:</b>
  <%= @landmark.longitude %>
</p>

<p>
  <b>URL:</b>
  <%= link_to @landmark.url, @landmark.url, target: "_blank" %>
</p>

<p>
  <b>クイズ:</b>
  <%= @landmark.question %>
</p>

<p>
  <b>答1:</b>
  <%= @landmark.answer1 %>
</p>

<p>
  <b>答2:</b>
  <%= @landmark.answer2 %>
</p>

<p>
  <b>答3:</b>
  <%= @landmark.answer3 %>
</p>

<p>
  <b>正解番号:</b>
  <%= @landmark.correct %>
</p>

<p>
  <b>作成者</b>
  <%= @landmark.author %>
</p>

<h2>タグ</h2>
<% @landmark.tags.each do |tag| %>
  <p>
    <%= tag.name %>
  </p>
<% end %>

<%= link_to '編集', edit_landmark_path(@landmark) %> |
<%= link_to '戻る', landmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kyotikaland</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>